# Конфигурация для инференса модели Аристотеля

# Модель
model_path: "./models"  # Путь к обученной модели

# API настройки
host: "0.0.0.0"  # Хост для API
port: 8000  # Порт для API
workers: 1  # Количество рабочих процессов
cors_origins:  # Разрешенные источники для CORS
  - "*"
version: "0.1.0"  # Версия API

# Параметры генерации по умолчанию
generation:
  max_length: 200  # Максимальная длина генерируемого текста
  num_return_sequences: 1  # Количество генерируемых вариантов
  temperature: 0.8  # Температура генерации (разнообразие)
  top_k: 50  # Параметр top-k для генерации
  top_p: 0.95  # Параметр top-p для генерации
  repetition_penalty: 1.2  # Штраф за повторения
  no_repeat_ngram_size: 2  # Размер n-грамм для предотвращения повторений
  do_sample: true  # Использовать сэмплирование вместо жадного декодирования

# Настройки логирования
log_level: "INFO"  # Уровень логирования
log_format: "json"  # Формат логов (json или text)

# Настройки мониторинга
monitoring:
  prometheus_enabled: true  # Включить метрики Prometheus
  request_latency_buckets:  # Бакеты для гистограммы задержки запросов
    - 0.01
    - 0.05
    - 0.1
    - 0.5
    - 1.0
    - 2.0
    - 5.0
    - 10.0

# Настройки кэширования
cache:
  enabled: false  # Включить кэширование результатов
  ttl: 3600  # Время жизни кэша в секундах
  max_size: 1000  # Максимальный размер кэша